// Writes the Swift tables from shared/data. Run from the repository root:
//
//   swift run --package-path Tools/Codegen codegen           write the files
//   swift run --package-path Tools/Codegen codegen --check   fail on drift, write nothing

import Foundation

// Static members, not top-level globals: top-level code in main.swift is main-actor isolated.
enum Paths {
  static let calendarJSON = "shared/data/calendar/bs-calendar.json"
  static let calendarOutput = "Sources/NepDate/Calendar.generated.swift"
}

let header = """
  // Generated by Tools/Codegen. DO NOT EDIT.
  // swift-format-ignore-file


  """

func fail(_ message: String) -> Never {
  FileHandle.standardError.write(Data("codegen: \(message)\n".utf8))
  exit(1)
}

struct CalendarFile: Decodable {
  let minYear: Int
  let maxYear: Int
  let monthLengths: [String: [Int]]

  enum CodingKeys: String, CodingKey {
    case minYear = "min_year"
    case maxYear = "max_year"
    case monthLengths = "month_lengths"
  }
}

/// Month lengths per year, in year order, after the checks of S0-02.
func loadMonthLengths() -> [(year: Int, lengths: [Int])] {
  let data: Data
  do {
    data = try Data(contentsOf: URL(fileURLWithPath: Paths.calendarJSON))
  } catch {
    fail("cannot read \(Paths.calendarJSON): \(error)")
  }
  let file: CalendarFile
  do {
    file = try JSONDecoder().decode(CalendarFile.self, from: data)
  } catch {
    fail("cannot decode \(Paths.calendarJSON): \(error)")
  }
  guard file.minYear == 1901 else { fail("min_year is \(file.minYear), expected 1901") }
  guard file.maxYear == 2199 else { fail("max_year is \(file.maxYear), expected 2199") }

  // JSON object order is not guaranteed, so sort the keys as numbers.
  var years: [(year: Int, lengths: [Int])] = []
  for (key, lengths) in file.monthLengths {
    guard let year = Int(key) else { fail("month_lengths key \"\(key)\" is not a year") }
    years.append((year, lengths))
  }
  years.sort { $0.year < $1.year }

  guard years.count == 299 else { fail("month_lengths has \(years.count) years, expected 299") }
  for (offset, entry) in years.enumerated() {
    guard entry.year == 1901 + offset else { fail("year \(1901 + offset) is missing") }
    guard entry.lengths.count == 12 else {
      fail("year \(entry.year) has \(entry.lengths.count) month lengths, expected 12")
    }
    for length in entry.lengths where !(29...32).contains(length) {
      fail("year \(entry.year) has a month of \(length) days, expected 29 to 32")
    }
  }
  return years
}

func calendarSource(_ years: [(year: Int, lengths: [Int])], header: String) -> String {
  var out = header
  out += """
    enum CalendarData {
      static let minYear = \(years[0].year)
      static let maxYear = \(years[years.count - 1].year)
    }

    """
  return out
}

/// Prints the first line where `expected` and the file on disk differ. Returns true when equal.
func matchesDisk(_ expected: String, path: String) -> Bool {
  guard let disk = FileManager.default.contents(atPath: path) else {
    print("codegen: \(path) is missing")
    return false
  }
  if disk == Data(expected.utf8) { return true }
  let actualLines = String(decoding: disk, as: UTF8.self).split(
    separator: "\n", omittingEmptySubsequences: false)
  let expectedLines = expected.split(separator: "\n", omittingEmptySubsequences: false)
  var line = 0
  while line < actualLines.count, line < expectedLines.count,
    actualLines[line] == expectedLines[line]
  {
    line += 1
  }
  let want = line < expectedLines.count ? String(expectedLines[line]) : "<end of file>"
  let got = line < actualLines.count ? String(actualLines[line]) : "<end of file>"
  print("codegen: \(path) differs from the generator at line \(line + 1)")
  print("  expected: \(want.debugDescription)")
  print("  actual:   \(got.debugDescription)")
  return false
}

let arguments = Array(CommandLine.arguments.dropFirst())
let check = arguments == ["--check"]
guard arguments.isEmpty || check else { fail("usage: codegen [--check]") }
guard FileManager.default.fileExists(atPath: "shared/VERSION") else {
  print("codegen: run from the repository root")
  exit(1)
}

let outputs = [(Paths.calendarOutput, calendarSource(loadMonthLengths(), header: header))]

if check {
  // Check every file before exiting, so one run reports all drift.
  let drifted = outputs.filter { !matchesDisk($0.1, path: $0.0) }
  if !drifted.isEmpty {
    print("codegen: run `swift run --package-path Tools/Codegen codegen` and commit the result")
    exit(1)
  }
  print("codegen: generated files are up to date")
} else {
  for (path, source) in outputs {
    do {
      try Data(source.utf8).write(to: URL(fileURLWithPath: path), options: .atomic)
    } catch {
      fail("cannot write \(path): \(error)")
    }
    print("codegen: wrote \(path)")
  }
}
