// Writes the Swift tables from shared/data. Run from the repository root:
//
//   swift run --package-path Tools/Codegen codegen           write the files
//   swift run --package-path Tools/Codegen codegen --check   fail on drift, write nothing

import Foundation

// Static members, not top-level globals: top-level code in main.swift is main-actor isolated.
enum Paths {
  static let calendarJSON = "shared/data/calendar/bs-calendar.json"
  static let calendarOutput = "Sources/NepDate/Calendar.generated.swift"
}

let header = """
  // Generated by Tools/Codegen. DO NOT EDIT.
  // swift-format-ignore-file


  """

func fail(_ message: String) -> Never {
  FileHandle.standardError.write(Data("codegen: \(message)\n".utf8))
  exit(1)
}

struct CalendarFile: Decodable {
  let minYear: Int
  let maxYear: Int
  let monthLengths: [String: [Int]]
  let epoch: Epoch

  struct Epoch: Decodable {
    let bs: String
    let ad: String
  }

  enum CodingKeys: String, CodingKey {
    case minYear = "min_year"
    case maxYear = "max_year"
    case monthLengths = "month_lengths"
    case epoch
  }
}

struct CalendarInput {
  let years: [(year: Int, lengths: [Int])]
  /// AD date of BS 1901-01-01, `YYYY-MM-DD`.
  let epochAD: String
  /// Unix day of `epochAD`.
  let epochUnixDays: Int
}

/// ALGORITHM §5, Hinnant's days_from_civil. Dev-time only, so plain `Int`.
func daysFromCivil(_ year: Int, _ month: Int, _ day: Int) -> Int {
  let y = month <= 2 ? year - 1 : year
  let era = (y >= 0 ? y : y - 399) / 400
  let yoe = y - era * 400
  let mp = (month + 9) % 12
  let doy = (153 * mp + 2) / 5 + day - 1
  let doe = yoe * 365 + yoe / 4 - yoe / 100 + doy
  return era * 146097 + doe - 719468
}

/// Month lengths per year, in year order, after the checks of S0-02, and the epoch.
func loadCalendar() -> CalendarInput {
  let data: Data
  do {
    data = try Data(contentsOf: URL(fileURLWithPath: Paths.calendarJSON))
  } catch {
    fail("cannot read \(Paths.calendarJSON): \(error)")
  }
  let file: CalendarFile
  do {
    file = try JSONDecoder().decode(CalendarFile.self, from: data)
  } catch {
    fail("cannot decode \(Paths.calendarJSON): \(error)")
  }
  guard file.minYear == 1901 else { fail("min_year is \(file.minYear), expected 1901") }
  guard file.maxYear == 2199 else { fail("max_year is \(file.maxYear), expected 2199") }

  // JSON object order is not guaranteed, so sort the keys as numbers.
  var years: [(year: Int, lengths: [Int])] = []
  for (key, lengths) in file.monthLengths {
    guard let year = Int(key) else { fail("month_lengths key \"\(key)\" is not a year") }
    years.append((year, lengths))
  }
  years.sort { $0.year < $1.year }

  guard years.count == 299 else { fail("month_lengths has \(years.count) years, expected 299") }
  for (offset, entry) in years.enumerated() {
    guard entry.year == 1901 + offset else { fail("year \(1901 + offset) is missing") }
    guard entry.lengths.count == 12 else {
      fail("year \(entry.year) has \(entry.lengths.count) month lengths, expected 12")
    }
    for length in entry.lengths where !(29...32).contains(length) {
      fail("year \(entry.year) has a month of \(length) days, expected 29 to 32")
    }
  }
  guard file.epoch.bs == "1901-01-01" else {
    fail("epoch.bs is \(file.epoch.bs), expected 1901-01-01")
  }
  let parts = file.epoch.ad.split(separator: "-").compactMap { Int($0) }
  guard parts.count == 3 else { fail("epoch.ad \(file.epoch.ad) is not YYYY-MM-DD") }
  return CalendarInput(
    years: years, epochAD: file.epoch.ad, epochUnixDays: daysFromCivil(parts[0], parts[1], parts[2])
  )
}

/// Index of the month that contains each serial, for the bucket table check.
func monthIndexOfSerial(_ monthStart: [Int]) -> [Int] {
  var result: [Int] = []
  result.reserveCapacity(monthStart[monthStart.count - 1])
  for i in 0..<(monthStart.count - 1) {
    for _ in monthStart[i]..<monthStart[i + 1] { result.append(i) }
  }
  return result
}

func calendarSource(_ calendar: CalendarInput, header: String) -> String {
  let years = calendar.years
  var monthStart = [0]
  for entry in years {
    for length in entry.lengths { monthStart.append(monthStart[monthStart.count - 1] + length) }
  }
  let totalDays = monthStart[monthStart.count - 1]

  // ADR-0002 §2: entry b is the month of serial b * 16. init(serial:) steps forward at most once,
  // so every serial of a bucket must lie in that month or the next.
  let monthOfSerial = monthIndexOfSerial(monthStart)
  let bucketCount = (totalDays + 15) / 16
  var monthAtBucket: [Int] = []
  for b in 0..<bucketCount {
    let first = monthOfSerial[b * 16]
    for s in (b * 16)..<min(b * 16 + 16, totalDays) where monthOfSerial[s] > first + 1 {
      fail("serial \(s) is two months after the start of its 16-day bucket")
    }
    monthAtBucket.append(first)
  }
  guard monthAtBucket.allSatisfy({ $0 <= Int(UInt16.max) }) else {
    fail("a month index does not fit in UInt16")
  }

  var out = header
  out += """
    /// Calendar tables from `shared/data/calendar/bs-calendar.json` (ADR-0002 §2).
    @usableFromInline
    enum CalendarData {
      @usableFromInline static let minYear = \(years[0].year)
      @usableFromInline static let maxYear = \(years[years.count - 1].year)
      /// Unix day of BS 1901-01-01 (AD \(calendar.epochAD)), ALGORITHM §2.
      @usableFromInline static let epochUnixDays: Int32 = \(calendar.epochUnixDays)
      /// Last valid serial, BS \(years[years.count - 1].year)-12-\(years[years.count - 1].lengths[11]).
      @usableFromInline static let maxSerial: Int32 = \(totalDays - 1)

      /// Serial of the first day of month index `(year - 1901) * 12 + month - 1`.
      /// \(monthStart.count) entries; the last one is the number of days in the range.
      @usableFromInline static let monthStart: [Int32] = [

    """
  for (offset, entry) in years.enumerated() {
    let row = monthStart[(offset * 12)..<(offset * 12 + 12)].map(String.init)
    out += "    \(row.joined(separator: ", ")), // \(entry.year)\n"
  }
  out += "    \(totalDays),\n  ]\n\n"
  out += """
      /// Month index of serial `b * 16`, for `b` in 0..<\(bucketCount).
      @usableFromInline static let monthAtBucket: [UInt16] = [

    """
  var index = 0
  while index < monthAtBucket.count {
    let row = monthAtBucket[index..<min(index + 16, monthAtBucket.count)].map(String.init)
    out += "    " + row.joined(separator: ", ") + ",\n"
    index += 16
  }
  out += "  ]\n}\n"
  return out
}

/// Prints the first line where `expected` and the file on disk differ. Returns true when equal.
func matchesDisk(_ expected: String, path: String) -> Bool {
  guard let disk = FileManager.default.contents(atPath: path) else {
    print("codegen: \(path) is missing")
    return false
  }
  if disk == Data(expected.utf8) { return true }
  let actualLines = String(decoding: disk, as: UTF8.self).split(
    separator: "\n", omittingEmptySubsequences: false)
  let expectedLines = expected.split(separator: "\n", omittingEmptySubsequences: false)
  var line = 0
  while line < actualLines.count, line < expectedLines.count,
    actualLines[line] == expectedLines[line]
  {
    line += 1
  }
  let want = line < expectedLines.count ? String(expectedLines[line]) : "<end of file>"
  let got = line < actualLines.count ? String(actualLines[line]) : "<end of file>"
  print("codegen: \(path) differs from the generator at line \(line + 1)")
  print("  expected: \(want.debugDescription)")
  print("  actual:   \(got.debugDescription)")
  return false
}

let arguments = Array(CommandLine.arguments.dropFirst())
let check = arguments == ["--check"]
guard arguments.isEmpty || check else { fail("usage: codegen [--check]") }
guard FileManager.default.fileExists(atPath: "shared/VERSION") else {
  print("codegen: run from the repository root")
  exit(1)
}

let outputs = [(Paths.calendarOutput, calendarSource(loadCalendar(), header: header))]

if check {
  // Check every file before exiting, so one run reports all drift.
  let drifted = outputs.filter { !matchesDisk($0.1, path: $0.0) }
  if !drifted.isEmpty {
    print("codegen: run `swift run --package-path Tools/Codegen codegen` and commit the result")
    exit(1)
  }
  print("codegen: generated files are up to date")
} else {
  for (path, source) in outputs {
    do {
      try Data(source.utf8).write(to: URL(fileURLWithPath: path), options: .atomic)
    } catch {
      fail("cannot write \(path): \(error)")
    }
    print("codegen: wrote \(path)")
  }
}
